export const MOVIES = [
  { id: 1, title: 'Dr. No', year: 1962, actor: 'Sean Connery' },
  { id: 2, title: 'From Russia with Love', year: 1963, actor: 'Sean Connery' },
  { id: 3, title: 'Goldfinger', year: 1964, actor: 'Sean Connery' },
  { id: 4, title: 'Thunderball', year: 1965, actor: 'Sean Connery' },
  { id: 5, title: 'You Only Live Twice', year: 1967, actor: 'Sean Connery' },
  { id: 6, title: 'On Her Majesty’s Secret Service', year: 1969, actor: 'George Lazenby' },
  { id: 7, title: 'Diamonds Are Forever', year: 1971, actor: 'Sean Connery' },
  { id: 8, title: 'Live and Let Die', year: 1973, actor: 'Roger Moore' },
  { id: 9, title: 'The Man with the Golden Gun', year: 1974, actor: 'Roger Moore' },
  { id: 10, title: 'The Spy Who Loved Me', year: 1977, actor: 'Roger Moore' },
  { id: 11, title: 'Moonraker', year: 1979, actor: 'Roger Moore' },
  { id: 12, title: 'For Your Eyes Only', year: 1981, actor: 'Roger Moore' },
  { id: 13, title: 'Octopussy', year: 1983, actor: 'Roger Moore' },
  { id: 14, title: 'A View to a Kill', year: 1985, actor: 'Roger Moore' },
  { id: 15, title: 'The Living Daylights', year: 1987, actor: 'Timothy Dalton' },
  { id: 16, title: 'Licence to Kill', year: 1989, actor: 'Timothy Dalton' },
  { id: 17, title: 'GoldenEye', year: 1995, actor: 'Pierce Brosnan' },
  { id: 18, title: 'Tomorrow Never Dies', year: 1997, actor: 'Pierce Brosnan' },
  { id: 19, title: 'The World Is Not Enough', year: 1999, actor: 'Pierce Brosnan' },
  { id: 20, title: 'Die Another Day', year: 2002, actor: 'Pierce Brosnan' },
  { id: 21, title: 'Casino Royale', year: 2006, actor: 'Daniel Craig' },
  { id: 22, title: 'Quantum of Solace', year: 2008, actor: 'Daniel Craig' },
  { id: 23, title: 'Skyfall', year: 2012, actor: 'Daniel Craig' },
  { id: 24, title: 'Spectre', year: 2015, actor: 'Daniel Craig' },
  { id: 25, title: 'No Time to Die', year: 2021, actor: 'Daniel Craig' }
];